### ISSUE TITLE
How to pass PushRoot?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [BoostingMy/vsts-heroku-tasks#1] opened 2016-02-19 06:38 UTC
I don't understand property PushRoot!

How to pass it?

I have added . and / ... both failed!

And the dialog of the path which appears when I click on the three dots button, only allows me to select a file under my repository but not the repository its self?!

**Comment by ahmed-abdulmoniem** [comment] 2016-02-19 06:50
@FernandoMorais?

**Comment by ahmed-abdulmoniem** [comment] 2016-02-20 05:56
Any hint please @FernandoMorais ?

**Comment by FernandoMorais** [comment] 2016-02-22 18:17
Hi @ahmed-abdulmoniem! 

How did you setup your release workflow?
You should select the root folder you want to publish on Heroku.

In my workflow I setup a build that runs Gulp and copy all files (except node_modules) to an output dir, after that it runs a release workflow that push to Heroku from that dir.

Give me more information on how you'd setup your workflow.

Regards,
Fernando

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 08:13
Hi @FernandoMorais 

I am using your task in the Build tasks of TFS.

I am pushing the whole repository to heroku so I don't create any folders?

**Comment by FernandoMorais** [comment] 2016-02-23 13:59
Is it a Node.js project?
Please, attach a screenshot from "select path" dialog to help me see how your folders are.

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 15:41
Yes, it is.

![image](https://cloud.githubusercontent.com/assets/6064145/13256755/9d2f3c18-da54-11e5-98d2-c15358f1bc96.png)

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 15:41
@FernandoMorais?

**Comment by FernandoMorais** [comment] 2016-02-23 16:30
Great!
Could yout post your Procfile content?

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 16:37
@FernandoMorais 

`web: slc run`

BTW .. when I select the path from the path dialog to be my repository name (the root) it is not selected and still the path is empty

**Comment by FernandoMorais** [comment] 2016-02-23 16:40
As a best practice I recommend you to create a "Copy and Publish Build Artifacts" or "Gulp" task that generates a "dist" folder, and then use that "dist" folder on Push Root. 

I recommend you to use Push To Heroku task on Release workflows, in that way you can push the same build output to different Heroku apps (which could be "stage" and "production" environments).

Just in case... If you want do push all your repository (something I would not recommend) you can set your Push Root to $(angent.builddirectory). Please, let me know if this solution worked. :)

Regards,
Fernando

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 16:45
Thank you. I am trying it ..

In some cases you can't do dist folder like in case of strongloop project which has specific folder structure and it must be sent as it is.

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 16:53
@FernandoMorais Still error

```
Copying files from 'C:\a\1\s\$(angent.builddirectory)'
Cannot find path 'C:\a\1\s\$(angent.builddirectory)' because it does not exist.
Files copied
Writing .gitignore file
Could not find a part of the path 'C:\a\1\s\$(angent.builddirectory)\.gitignore'.
.gitignore written
Initializing git config
git config --local user.name ""
git config --local user.email "vsts@[MY_APPLICATION_NAME].git.heroku.com"
Git config initialized
Adding files
git add .
[git] fatal: Not a git repository (or any of the parent directories): .git
******************************************************************************
Finishing task: PushToHeroku
******************************************************************************
Task PushToHeroku failed. This caused the job to fail. Look at the logs for the task for more details.
******************************************************************************
```

![image](https://cloud.githubusercontent.com/assets/6064145/13259124/b61a29f4-da5e-11e5-8c86-166b4041bbe9.png)

**Comment by FernandoMorais** [comment] 2016-02-23 17:01
Please, set the "system.debug" variable to "true", that will let us to see a verbose log for the task. 
It will help us to find exactly where is the problem.

**Comment by FernandoMorais** [comment] 2016-02-23 17:17
@ahmed-abdulmoniem I've tested on Build workflow and the task will not work because of lack of some environment variables used during the execution. You must use a Release workflow instead.

Use a "Copy and Publish Build Artifacts" to create a "drop" folder:
![image](https://cloud.githubusercontent.com/assets/13754346/13259785/ab51993e-da37-11e5-8d5b-fdd2ca587fbe.png)

And then on Release workflow configure the Push to Heroku task as follows:
![image](https://cloud.githubusercontent.com/assets/13754346/13259888/107dc47c-da38-11e5-98c0-9656b8f5f67c.png)

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 17:20
@FernandoMorais You mean I must use the Release management component not TFS build?

**Comment by FernandoMorais** [comment] 2016-02-23 17:27
Yes!
By design, the task depends on Release environment variables, that are not present on Build workflows.

BTW, it is a best practice since you could target multiple Heroku Apps with the same build output, creating stage and production environment/apps. :)

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 17:32
OK thank you. I will try the new release management component.

**Comment by FernandoMorais** [comment] 2016-02-23 17:35
OK! Let me know if it works!

**Comment by ahmed-abdulmoniem** [comment] 2016-02-23 17:35
Sure

**Comment by FernandoMorais** [comment] 2016-03-05 02:53
Hi @ahmed-abdulmoniem!

Just to follow up, did it work ok?

**Comment by ahmed-abdulmoniem** [comment] 2016-03-05 16:01
Still didn't setup the release management component @FernandoMorais

**Comment by FernandoMorais** [comment] 2016-03-29 01:18
Hi @ahmed-abdulmoniem! Did you try using release management?

**Comment by ahmed-abdulmoniem** [comment] 2016-10-21 02:34
I have been able to make it working using release management

But ... I am facing the same as this: https://github.com/BoostingMy/vsts-heroku-tasks/issues/2

**Comment by ahmed-abdulmoniem** [comment] 2016-10-21 02:36
@FernandoMorais ?

**Comment by FernandoMorais** [comment] 2016-10-25 17:08
Hi @ahmed-abdulmoniem, I'll close this issue and solve the new problem described at #2!

**Closed as completed by FernandoMorais** 2016-10-25 17:08 UTC
